exports.seed = function(knex) {
  return knex("items").insert([
    {
      id: 1,
      event_id: 1,
      item: "picnic chairs",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 2,
      event_id: 1,
      item: "picnic tables",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 3,
      event_id: 1,
      item: "food",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 4,
      event_id: 1,
      item: "drinks",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 5,
      event_id: 1,
      item: "entertainment",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 6,
      event_id: 2,
      item: "napkins",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 7,
      event_id: 2,
      item: "taco trunk",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 8,
      event_id: 2,
      item: "soda",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 9,
      event_id: 3,
      item: "balloons",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 10,
      event_id: 3,
      item: "catering",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 11,
      event_id: 4,
      item: "stuffed animals",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 12,
      event_id: 4,
      item: "food",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 13,
      event_id: 5,
      item: "water balloons",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 14,
      event_id: 5,
      item: "toy water guns",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 15,
      event_id: 6,
      item: "gift bags",
      quantity: null,
      cost: 0,
      completed: false,
    },
    {
      id: 16,
      event_id: 6,
      item: "catering",
      quantity: null,
      cost: 0,
      completed: false,
    },
  ]);
};
